# Generated by Django 5.1.3 on 2024-11-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_for_user',
            field=models.IntegerField(default=0),
        ),
    ]
