# Generated by Django 5.1.3 on 2024-11-17 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_quantity_for_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity_for_user',
        ),
    ]
