# Generated by Django 5.0.1 on 2025-02-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_product_quantity_for_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_quantity',
            field=models.IntegerField(default=0, verbose_name='Recommended Quantity'),
        ),
    ]
