# Generated by Django 5.0.1 on 2024-05-20 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liter',
            field=models.FloatField(blank=True, null=True, verbose_name='Container Volume (liters)'),
        ),
        migrations.AddField(
            model_name='product',
            name='viscosity',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Viscosity Grade'),
        ),
    ]
