# Generated by Django 5.1.6 on 2025-02-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_viscosity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='viscosity',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Viscosity Grade'),
        ),
    ]
