# Generated by Django 5.0.1 on 2024-04-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payout_transaction_admin_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payout',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='admin_amount',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='vendor_amount',
        ),
    ]
