# Generated by Django 5.1.3 on 2024-11-17 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilchangedelivery', '0001_initial'),
        ('product', '0004_remove_product_quantity_for_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilchangedelivery',
            name='car_make_model_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='oilchangedelivery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
