# Generated by Django 5.0.1 on 2024-09-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilchangedelivery', '0002_alter_oilchangedelivery_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilchangedelivery',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
