# Generated by Django 5.1.3 on 2024-11-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilchangedelivery', '0003_oilchangedelivery_ordered_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oilchangedelivery',
            name='product',
        ),
        migrations.AlterField(
            model_name='oilchangedelivery',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
