# Generated by Django 5.1.3 on 2024-11-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oilchangedelivery', '0004_remove_oilchangedelivery_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oilchangedelivery',
            name='message',
        ),
    ]
