# Generated by Django 5.1.3 on 2024-11-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oilchangedelivery', '0005_remove_oilchangedelivery_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='oilchangedelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
