# Generated by Django 5.1.3 on 2024-11-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order_status',
        ),
    ]
