# Generated by Django 5.0.1 on 2025-02-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
