# Generated by Django 5.0.1 on 2024-03-09 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_refreshtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
