# Generated by Django 5.0.1 on 2024-03-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paypal_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
