# Generated by Django 5.0.1 on 2024-09-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_address_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='car_make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='car_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='car_vin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='car_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
