# Generated by Django 5.0.1 on 2024-10-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_mainpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
