# Generated by Django 5.1.3 on 2024-11-26 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
