# Generated by Django 5.0.1 on 2025-01-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_courier_name_order_courier_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
