# Generated by Django 5.0.1 on 2025-01-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderitem_delivery_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivery_time',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
