# Generated by Django 5.0.1 on 2025-02-01 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_email'),
        ('product', '0004_remove_product_quantity_for_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveIntegerField(help_text='Mileage of the car in kilometers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oil_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='Selected Oil Product')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_orders', to='order.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
