# Generated by Django 5.0.1 on 2025-02-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_savedorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, help_text='Mileage of the car in kilometers', null=True),
        ),
        migrations.AlterField(
            model_name='savedorder',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, help_text='Mileage of the car in kilometers', null=True),
        ),
    ]
