# Generated by Django 5.0.1 on 2025-02-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_order_mileage_alter_savedorder_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='recommended_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
