# Generated by Django 5.0.1 on 2025-02-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_orderitem_recommended_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('pending', 'Pending'), ('paid', 'Paid')], default='not_paid', max_length=20),
        ),
    ]
