# Generated by Django 5.0.1 on 2025-02-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedorder',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='savedorder',
            name='oil_used',
        ),
        migrations.RemoveField(
            model_name='savedorder',
            name='order',
        ),
        migrations.RemoveField(
            model_name='savedorder',
            name='user',
        ),
        migrations.AddField(
            model_name='savedorder',
            name='order_data',
            field=models.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('completed', 'Completed'), ('failed', 'Failed'), ('pending', 'Pending'), ('not_paid', 'Not Paid')], default='not_paid', max_length=20),
        ),
    ]
