# Generated by Django 5.0.1 on 2025-02-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_remove_savedorder_mileage_remove_savedorder_oil_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedorder',
            name='order_data',
            field=models.JSONField(default=dict),
        ),
    ]
